"use client";

import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, Check, ChevronDown, Menu, X, Workflow, MonitorSmartphone, Database, Megaphone, MessageCircle, Boxes, ExternalLink } from "lucide-react";
import { projects } from "../app/websites/data/projects";

const outcomes = [
  ["Get found", "Websites, landing pages, e-commerce, branding and social design.", MonitorSmartphone],
  ["Automate", "WhatsApp workflows, customer follow-ups, CRM and AI automation.", Workflow],
  ["Operate", "POS, inventory, booking and business management software.", Database],
  ["Grow", "Meta ads, lead generation and conversion optimisation.", Megaphone],
];
const problems = ["Manual record keeping", "Missed customer follow-ups", "Disconnected tools", "Repetitive admin work", "A weak online presence", "Complicated booking flows"];
const process = ["Understand", "Plan", "Design", "Build", "Launch", "Grow"];
const faqs = [
  ["How much does custom software cost?", "Pricing depends on the scope, number of users, integrations and complexity. We start by understanding the problem, then provide a clear proposal for the right solution."],
  ["Can you build software specifically for my business?", "Yes. FORESTY designs systems around your workflow instead of asking your team to adapt to generic software."],
  ["Can you integrate WhatsApp?", "Yes. We can design WhatsApp automation and customer flows using the appropriate official APIs and infrastructure for your use case."],
  ["Do you provide maintenance after launch?", "Support and improvement plans can be scoped alongside your build, so the system stays useful as your business changes."],
  ["How long does development take?", "A focused website can move quickly; larger software products need discovery and planning first. Your proposal will include an honest timeline."],
];

const Button = ({ children, href = "#contact", secondary = false, className = "" }) => <a href={href} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-full px-5 text-sm font-semibold transition duration-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#b4e63a] ${secondary ? "border border-white/20 text-white hover:border-[#b4e63a] hover:text-[#d6ff65]" : "bg-[#b4e63a] text-[#10200b] hover:-translate-y-0.5 hover:bg-[#d6ff65]"} ${className}`}>{children}<ArrowRight size={16}/></a>;

function ProjectModal({ project, close }) {
  useEffect(() => { const key = e => e.key === "Escape" && close(); window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [close]);
  return <AnimatePresence>{project && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={close} className="fixed inset-0 z-[100] grid place-items-center bg-[#071005]/85 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={`${project.title} case study`}>
    <motion.article initial={{opacity:0,y:24,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:16}} transition={{duration:.25}} onMouseDown={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-[1.5rem] border border-white/10 bg-[#10170e] text-white shadow-2xl">
      <div className="relative aspect-[16/7] overflow-hidden"><img src={project.image} alt={project.alt} className="h-full w-full object-cover"/><button onClick={close} aria-label="Close case study" className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-black/60 hover:bg-[#b4e63a] hover:text-black"><X size={19}/></button></div>
      <div className="grid gap-8 p-6 sm:p-10 md:grid-cols-[1.2fr_.8fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#b4e63a]">{project.industry} · {project.category}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">{project.title}</h2><h3 className="mt-8 text-sm font-bold uppercase tracking-wider text-white/50">The challenge</h3><p className="mt-2 leading-7 text-white/70">Creating a clear, credible digital experience that makes it easier for customers to discover the business and take action.</p><h3 className="mt-7 text-sm font-bold uppercase tracking-wider text-white/50">Our solution</h3><p className="mt-2 leading-7 text-white/70">{project.about}</p></div><aside><h3 className="text-sm font-bold uppercase tracking-wider text-white/50">Key features</h3><div className="mt-3 flex flex-wrap gap-2">{project.services.map(x=><span key={x} className="rounded-full border border-[#b4e63a]/30 bg-[#b4e63a]/10 px-3 py-1.5 text-xs text-[#d6ff65]">{x}</span>)}</div><h3 className="mt-8 text-sm font-bold uppercase tracking-wider text-white/50">Technology</h3><p className="mt-3 text-sm text-white/75">{project.technologies.join(" · ")}</p><div className="mt-8 rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-white/60">Client testimonial will be added when approved by the client.</div>{project.projectUrl && <a className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#d6ff65]" href={project.projectUrl} target="_blank" rel="noreferrer">Visit project <ExternalLink size={15}/></a>}</aside></div>
    </motion.article></motion.div>}</AnimatePresence>;
}

export default function PremiumSite() {
 const [menu, setMenu] = useState(false), [selected, setSelected] = useState(null), [open, setOpen] = useState(null);
 const nav = [["Solutions","#solutions"],["Projects","#projects"],["Process","#process"],["About","#about"]];
 return <main className="min-h-screen bg-[#091006] font-sans text-[#f3f6ec] selection:bg-[#b4e63a] selection:text-black">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#091006]/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5"><a href="#home" className="text-lg font-black tracking-[.18em]">FORESTY<span className="text-[#b4e63a]">.</span></a><nav className="hidden gap-7 md:flex">{nav.map(([x,h])=><a key={x} href={h} className="text-sm text-white/70 transition hover:text-[#d6ff65]">{x}</a>)}</nav><div className="hidden md:block"><Button>Start a Project</Button></div><button className="md:hidden" aria-label="Open navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="border-t border-white/10 px-5 py-5 md:hidden">{nav.map(([x,h])=><a onClick={()=>setMenu(false)} key={x} href={h} className="block py-3 text-lg">{x}</a>)}<Button className="mt-3 w-full">Start a Project</Button></nav>}</header>
  <section id="home" className="relative overflow-hidden px-5 pb-20 pt-36 sm:pb-28"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(rgba(180,230,58,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(180,230,58,.06)_1px,transparent_1px)] [background-size:52px_52px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1fr_.9fr]"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.65}}><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">Digital systems for ambitious businesses</p><h1 className="max-w-3xl text-5xl font-semibold leading-[.96] tracking-[-.06em] sm:text-7xl">Technology built around <span className="text-[#b4e63a]">your business.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/65">We design websites, automate workflows, and build custom software that solves real business problems.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button>Start a Project</Button><Button secondary href="#projects">See Our Work</Button></div></motion.div><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.7,delay:.15}} className="relative rounded-[2rem] border border-[#b4e63a]/25 bg-[#111b0d] p-3 shadow-[0_40px_100px_rgba(0,0,0,.45)]"><div className="rounded-[1.5rem] border border-white/10 bg-[#0b1109] p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4 text-xs text-white/50"><span>FORESTY / OPERATIONS</span><span className="rounded-full bg-[#b4e63a] px-2 py-1 font-bold text-[#13200d]">CONNECTED</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="col-span-2 rounded-xl bg-[#b4e63a] p-5 text-[#17230f]"><p className="text-xs font-bold uppercase tracking-widest">Business overview</p><p className="mt-4 text-3xl font-semibold">Everything, in flow.</p></div>{["Customers","Bookings","Follow-ups","Reports"].map((x,i)=><div key={x} className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/45">0{i+1}</p><p className="mt-6 font-medium">{x}</p><div className="mt-3 h-1 rounded bg-[#b4e63a]/70"/></div>)}</div></div></motion.div></div></section>
  <section className="border-y border-white/10 bg-[#10190c] px-5 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">The real problem</p><div className="mt-5 grid gap-10 lg:grid-cols-2"><h2 className="max-w-2xl text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Your business shouldn&apos;t be held together by spreadsheets, WhatsApp messages and manual work.</h2><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10">{problems.map((x,i)=><div key={x} className="bg-[#10190c] p-5"><span className="text-xs text-[#b4e63a]">0{i+1}</span><p className="mt-8 text-sm leading-6 text-white/75">{x}</p></div>)}</div></div></div></section>
  <section id="solutions" className="px-5 py-24"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">One connected partner</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Everything your business needs to go digital.</h2></div><div className="mt-12 grid gap-3 md:grid-cols-2">{outcomes.map(([title,copy,Icon],i)=><article key={title} className="group rounded-2xl border border-white/10 bg-[#10170e] p-7 transition hover:-translate-y-1 hover:border-[#b4e63a]/45"><div className="flex items-start justify-between"><Icon className="text-[#b4e63a]"/><span className="text-sm text-white/35">0{i+1}</span></div><h3 className="mt-16 text-2xl font-semibold">{title}</h3><p className="mt-3 max-w-sm leading-7 text-white/60">{copy}</p></article>)}</div></div></section>
  <section id="projects" className="bg-[#10190c] px-5 py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">Selected work</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Real problems. Real software.</h2></div><Button secondary href="/websites">All projects</Button></div><div className="mt-12 grid gap-6 md:grid-cols-3">{projects.map(p=><button key={p.id} onClick={()=>setSelected(p)} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#0b1109] text-left transition hover:-translate-y-1 hover:border-[#b4e63a]/45"><div className="aspect-[4/3] overflow-hidden"><img src={p.image} alt={p.alt} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#b4e63a]">{p.industry}</p><h3 className="mt-3 text-xl font-semibold">{p.title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-white/60">{p.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold">View project <ArrowRight size={15}/></span></div></button>)}</div></div></section>
  <section id="process" className="px-5 py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">How we work</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">From problem → product.</h2><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{process.map((x,i)=><div key={x} className="border-t border-[#b4e63a]/50 pt-4"><span className="text-xs text-[#b4e63a]">0{i+1}</span><h3 className="mt-8 text-lg font-semibold">{x}</h3><p className="mt-2 text-sm leading-6 text-white/55">{["We learn your workflow and pain points.","We define the right technical direction.","We make the experience clear and intuitive.","We develop the product and integrations.","We deploy it for real-world use.","We improve as your business evolves."][i]}</p></div>)}</div></div></section>
  <section className="border-y border-white/10 bg-[#10170e] px-5 py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">Why FORESTY</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Built to fit the way you work.</h2><p className="mt-5 max-w-lg leading-7 text-white/65">Businesses don&apos;t need more software for the sake of software. They need technology that makes work easier.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Built around your business","Real projects, not promises","Connected systems","Built to evolve","Practical solutions","Direct communication"].map(x=><div key={x} className="flex gap-3 border-b border-white/10 py-4 text-sm font-medium"><Check className="shrink-0 text-[#b4e63a]" size={18}/>{x}</div>)}</div></div></section>
  <section className="px-5 py-24"><div className="mx-auto max-w-5xl"><p className="text-center text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">The difference</p><h2 className="mt-4 text-center text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Generic software vs software built for you.</h2><div className="mt-12 overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-2 bg-white/5 p-4 text-xs font-bold uppercase tracking-wider text-white/55"><span>Generic software</span><span className="text-[#b4e63a]">FORESTY</span></div>{[["You adapt to the software","Software adapts to your workflow"],["Unnecessary features","Only what your business needs"],["Disconnected tools","Connected systems"],["Limited flexibility","Built to evolve"]].map(([a,b])=><div key={a} className="grid grid-cols-2 border-t border-white/10 p-4 text-sm text-white/65"><span>{a}</span><span className="text-white">{b}</span></div>)}</div></div></section>
  <section id="about" className="bg-[#b4e63a] px-5 py-24 text-[#11200c]"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em]">Behind FORESTY</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Technology should make a business easier to run.</h2></div><p className="max-w-xl self-end text-lg leading-8 text-[#25401b]">FORESTY exists to turn everyday business friction into clear digital systems — from the first customer impression through to the work happening behind the scenes.</p></div></section>
  <section className="px-5 py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b4e63a]">Straight answers</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">Questions worth asking.</h2></div><div>{faqs.map(([q,a],i)=><div className="border-b border-white/10" key={q}><button className="flex w-full items-center justify-between gap-5 py-5 text-left font-medium" onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}>{q}<ChevronDown className={`shrink-0 transition ${open===i?"rotate-180 text-[#b4e63a]":""}`}/></button>{open===i&&<p className="max-w-2xl pb-5 leading-7 text-white/60">{a}</p>}</div>)}</div></div></section>
  <section id="contact" className="px-5 pb-20"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[#f0f5e7] px-7 py-14 text-[#10200b] sm:px-14 sm:py-20"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#527c1c]">Let&apos;s talk</p><h2 className="mt-4 max-w-3xl text-5xl font-semibold tracking-[-.055em] sm:text-7xl">Have a business problem? Let&apos;s build the solution.</h2><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button href="https://wa.me/923195403032">Start a Project</Button><Button href="#projects" secondary>See Our Work</Button></div></div></section>
  <footer className="border-t border-white/10 px-5 py-9"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-sm text-white/55 sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-white">FORESTY.</strong><span className="ml-3">Digital systems for better businesses.</span></div><div className="flex gap-5"><a href="https://instagram.com/foresty_nexus" target="_blank" rel="noreferrer">Instagram</a><a href="https://wa.me/923195403032" target="_blank" rel="noreferrer">WhatsApp</a></div></div></footer>
  <ProjectModal project={selected} close={()=>setSelected(null)}/>
 </main>;
}
